services:
  - type: web
    name: ria-artisan-king-george
    env: node
    plan: free
    buildCommand: ""
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ADMIN_TOKEN
        value: demo123
