services:
  - type: web
    name: ria-artisan-king-george
    env: node
    plan: free
    buildCommand: npm install --registry=https://registry.npmjs.org/
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ADMIN_TOKEN
        sync: false
