services:
  - type: web
    name: ria-artisan-king-george
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_TOKEN
        sync: false
